### PR TITLE
Spot price calculation functionality

### PR DESCRIPTION
**Pull request by achave11-ucsc**
**TESTED in DEV-MODE**
Modifications to the `generate_billing` script in order to account for spot prices, instead of static prices.

### CODE REVIEW

**Review by caaespin — COMMENTED** [review]
@achave11 , do you know what boto version you used?

**Comment by achave11-ucsc** [comment]
@caaespin `boto3==1.4.4` it should have been included in the `requirements.txt`

**Review by caaespin — CHANGES_REQUESTED** [review]
I get a botocore.exceptions.NoCredentialsError when running it. You can go and try to go 2 ways about this:

You can either config Boto within the python script (see this https://stackoverflow.com/questions/33297172/boto3-error-botocore-exceptions-nocredentialserror-unable-to-locate-credential), 

or you can edit the run2.sh bash script to place the credentials in a file by reading off from environmental variables (e.g.       AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY passed on at runtime to the container). This would be the preferred way.  The code that gets run with the cronjob flag code only gets run the first time the containers gets brought up to life, so you can make use of that when setting up things.

**Review by caaespin — APPROVED** [review]
LGTM

**Pull request merged**
