### PR TITLE
Feature/#30 finalize schema

### PR DESCRIPTION
**Pull request by chkw**
@briandoconnor , can you take a look at this new version of the `metadata_schema.json`? I think it is ready to merge with develop. Jean has been using it as to validate his merged metadata, and it seems to be working.

### CODE REVIEW

**Comment by chkw** [comment]
I went ahead and added an analysis-only schema for validating analysis-only objects. The file for that is `analysis_schema.json`.

**Comment by briandoconnor** [comment]
Missing dependency in the pip install:

```
Traceback (most recent call last):
  File "generate_metadata.py", line 23, in <module>
    import semver
ImportError: No module named semver
```

**Comment by briandoconnor** [comment]
Is the receipt.tsv output feature broken?  I ran the sample call and don't see a receipt.tsv file in the current directory (or sub-directories).

```
(env) boconnor@Work-MacBook-Pro:~/Development/gitroot/BD2KGenomics/dcc-storage-schemas$ python generate_metadata.py         --inputMetadataSchema input_metadata.json         --metadataSchema metadata_schema.json         --outputDir output_metadata         --receiptFile receipt.tsv         --awsAccessToken `cat ucsc-storage-client/accessToken`         --skip-upload         sample_tsv/sample.tsv
2016-07-29 16:35:01,004 INFO main:730 couldn't read sample_tsv/sample.tsv as excel file
2016-07-29 16:35:01,004 INFO main:731 ---now trying to read as tsv file
2016-07-29 16:35:01,280 INFO main:766 validated all metadata objects for output
2016-07-29 16:35:01,302 INFO main:770 number of metadata files written: 43
2016-07-29 16:35:01,302 INFO main:773 Skipping data upload steps.
2016-07-29 16:35:01,303 INFO main:774 A detailed log is at: output_metadata/generate_metadata.log
2016-07-29 16:35:01,303 INFO main:776 program ran for 0.299878 s.
(env) boconnor@Work-MacBook-Pro:~/Development/gitroot/BD2KGenomics/dcc-storage-schemas$ find . | grep receipt.tsv
(env) boconnor@Work-MacBook-Pro:~/Development/gitroot/BD2KGenomics/dcc-storage-schemas$
```

Oh wait, the receipt only activated when doing an upload, right?

**Comment by briandoconnor** [comment]
I haven't tested upload but the metadata looks OK.  Also, I just tested `generate_metadata.py` and not the downstream index builder since Jean is working on this.

**Pull request merged**
