### PR TITLE
Feature/#17 single metadata per donor

### PR DESCRIPTION
**Pull request by chkw**
Instead of separate biospecimen.json and analysis.json files, create one metadata.json file per donor that has all of the donor metadata.  The upload portion of generate_metadata.py needs to be updated to be aware of this change.

### CODE REVIEW

**Comment by briandoconnor** [comment]
@chkw your readme needs to be updated, the following is incorrect:

```
python generate_metadata.py -v \
--biospecimenSchema biospecimen_flattened.json \
--analysisSchema analysis_flattened.json \
sample_tsv/sample.tsv
```

**Comment by briandoconnor** [comment]
@chkw our wires are crossed here... you interpreted this as "one metadata.json per donor" and I was talking about "one metadata.json per upload".  Let's discuss in person today.  See #17

**Comment by briandoconnor** [comment]
Including the workflows in a workflow array breaks `merge_generated_metadata.py` and `esquery.py`.  You need to update these (after addressing the problem above) before I can merge the branch.

**Comment by briandoconnor** [comment]
Does this do the file upload and metadata.json uploads in two seperate calls with Beni's tool!?!

```
INFO:root:First, upload workflow outputs to get file_uuids.
INFO:root:done uploading files
INFO:root:upload took 0:03:54.068985 s for 48 files.
INFO:root:Now, upload metadata json files.
```

It can't be done this way since the metadata.json and files uploaded need to be done at the same time so everything is logically grouped in the same upload bundle.

**Comment by briandoconnor** [comment]
Can you walk me through the uploads done and how they are done?  I see the following:

```
(env) boconnor@Brians-Mac-Pro:~/Development/gitroot/BD2KGenomics/dcc-storage-schemas$ ls -lth output_metadata/088bda20-30d2-5944-a5fd-fee9a223f1a7/
total 128
-rw-r--r--  1 boconnor  staff   470B Jun 20 16:39 2d49242e-b8f9-50ff-b304-158588382735_alignment.json
-rw-r--r--  1 boconnor  staff   679B Jun 20 16:39 45ce9304-1fb1-5b18-be69-8463cf8532b6_somatic_variant_calling.json
-rw-r--r--  1 boconnor  staff   485B Jun 20 16:39 5c58e075-a2ba-536c-b039-f0418746dcea_sequence_upload.json
-rw-r--r--  1 boconnor  staff   486B Jun 20 16:39 6132a741-090d-5fb8-99d9-a68204843657_germline_variant_calling.json
-rw-r--r--  1 boconnor  staff   490B Jun 20 16:39 84e9bb68-6109-5f57-9f25-b2421d3bc2f6_rna_seq_quantification.json
-rw-r--r--  1 boconnor  staff   471B Jun 20 16:39 854d1130-e1fc-57d8-bd93-9e38831e334d_alignment.json
-rw-r--r--  1 boconnor  staff   486B Jun 20 16:39 ca3ccf42-c0ea-553b-b19f-e34570a1f03c_sequence_upload.json
-rw-r--r--  1 boconnor  staff   1.1K Jun 20 16:35 088bda20-30d2-5944-a5fd-fee9a223f1a7_biospecimen.json
lrwxr-xr-x  1 boconnor  staff    98B Jun 20 16:35 2d49242e-b8f9-50ff-b304-158588382735_tumor.bam@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/tumor.bam
lrwxr-xr-x  1 boconnor  staff   106B Jun 20 16:35 45ce9304-1fb1-5b18-be69-8463cf8532b6_somatic.indel.vcf@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/somatic.indel.vcf
lrwxr-xr-x  1 boconnor  staff   104B Jun 20 16:35 45ce9304-1fb1-5b18-be69-8463cf8532b6_somatic.snv.vcf@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/somatic.snv.vcf
lrwxr-xr-x  1 boconnor  staff   103B Jun 20 16:35 5c58e075-a2ba-536c-b039-f0418746dcea_tumor.fastq.gz@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/tumor.fastq.gz
lrwxr-xr-x  1 boconnor  staff   101B Jun 20 16:35 6132a741-090d-5fb8-99d9-a68204843657_germline.vcf@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/germline.vcf
lrwxr-xr-x  1 boconnor  staff   109B Jun 20 16:35 84e9bb68-6109-5f57-9f25-b2421d3bc2f6_gene_expression.rsem@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/gene_expression.rsem
lrwxr-xr-x  1 boconnor  staff    99B Jun 20 16:35 854d1130-e1fc-57d8-bd93-9e38831e334d_normal.bam@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/normal.bam
lrwxr-xr-x  1 boconnor  staff   104B Jun 20 16:35 ca3ccf42-c0ea-553b-b19f-e34570a1f03c_normal.fastq.gz@ -> /Users/boconnor/Development/gitroot/BD2KGenomics/dcc-storage-schemas/sample_upload_files/normal.fastq.gz
```

But I thought the structure would be more like:

```
output_metadata/<uuid_for_program+project+donor_id>/<uuid_for_data_bundle>/metadata.json 
                                                                     /vcf files etc

```

**Comment by briandoconnor** [comment]
Related to the comment above, I think I know why you tried to do an upload in two parts, first the workflow_outputs you have include the file upload UUID.  You won't actual know this since you need to do the file upload and metadata.json upload at the same time.  What we could do is include the databundle ID in the workflow metadata.json.

Let's talk about this tomorrow.

**Comment by briandoconnor** [comment]
Another comment, I still see a separate biospecimen.json:

```
088bda20-30d2-5944-a5fd-fee9a223f1a7_biospecimen.json
```

I thought you would merge this?

I think you and I should just go over the metadata files and review this pull request together tomorrow.  It will be faster than leaving comments here.  I think you're close to having this right but I want to make sure we agree on the final format.

**Comment by chkw** [comment]
It seems that ucsc-upload.sh works in 2 steps (with one java call per step).... The first step is generating a manifest file which is used in the second step for the actual file uploading. The manifest file contains the 'object ids' for each file in the upload. Since we're planning on reimplementing the functionality of ucsc-upload.sh, maybe we could get the file_uuids from there and add the "file_uuid" to metadata.json between manifest generation and file upload.

One problem that I was running into was files that have identical file names seem to get clobbered/ignored by ucsc-upload.sh, even if they are found in different paths. This means that only one "metadata.json" can be uploaded at a time. Actually, I don't know what really happens if you upload a "metadata.json" in a subsequent upload. The upload completes, but does it replace the old one, or do they coexist together? What happens to the assigned object ids?

**Comment by briandoconnor** [comment]
So the new per-upload UUID directory looks good, the `generate_metadata.py` script looks good.  But the downstream script will need some tweaks

```
(env) boconnor@Brians-Mac-Pro:~/Development/gitroot/BD2KGenomics/dcc-storage-schemas$ python merge_generated_metadata.py `for i in output_metadata/*; do echo -n "$i "; done`
FILE! output_metadata/1329abd5-a293-5a20-a32e-a31b7f37799d/gene_expression.rsem
Traceback (most recent call last):
  File "merge_generated_metadata.py", line 190, in <module>
    donor_uuid_arr = find_values('donor_uuid', json_data)
  File "merge_generated_metadata.py", line 171, in find_values
    json.loads(json_repr, object_hook=_decode_dict)  # return value ignored
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Pull request merged**
