### PR TITLE
Feature/cnvflags

### PR DESCRIPTION
**Pull request by tboser**
Updates metadata indexer to include a flag for the CNV workflow.

### CODE REVIEW

**Comment by caaespin** [comment]
@tboser , doesn't the schema need to be updated as well? If it needs to, was it updated for the previous pull request you made a while back?

https://github.com/BD2KGenomics/dcc-metadata-indexer/blob/feature/cnvflags/v2/metadata_schema.json,

https://github.com/BD2KGenomics/dcc-metadata-indexer/blob/feature/cnvflags/metadata_schema.json

**Comment by tboser** [comment]
@caaespin ah yeah, i missed that. i'll update the schema and i've got a change i want to make to the indexer as well. i'll let you know when it's ready.

**Comment by tboser** [comment]
@caaespin I've looked at the schema, I don't think it needs to be updated for the flags I'm changing (but I may be mistaken). There is also no quay repository for this project so I'll be leaving the urls unchanged for now. So as of now this is all the changes I can make, if you're going to be testing the new metadata indexer it'd be useful for me if you included these changes. Let me know if I'm missing something, thanks.

**Comment by wshands** [comment]
I think we do have to update the schema; for instance I believe under analysis|analysis_type in the enum we need an entry for the CNV and PROTECT pipelines, e.g. cnv_variant_calling, protect_???

We will also need entries under 'flags' and 'missing_items' for CNV and PROTECT

Take a look at a validated json metadata entry to see the missing, present, and flags sections.

**Comment by tboser** [comment]
@caaespin @wshands I've updated the schema, could you please look over it to make sure it's updated properly? I added missing flags etc for RNA-seq, protect, and CNV.

**Comment by caaespin** [comment]
LGTM. @wshands , can you double check the flags and make sure it is what you need?

**Pull request merged**
